'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';

type Skill = { id: string; name: string; category: string };
export default function OnboardingForm({ skills = [], profile, demo = false }: { skills?: Skill[]; profile?: any; demo?: boolean }) {
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [form, setForm] = useState({ full_name: profile?.full_name ?? '', district: profile?.district ?? '', bio: profile?.bio ?? '', session_type: profile?.session_type ?? 'Online', languages: (profile?.languages ?? []).join(', ') });
  const [teach, setTeach] = useState<string[]>([]);
  const [learn, setLearn] = useState<string[]>([]);
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async () => {
    const response = await fetch('/api/profiles', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, languages: form.languages.split(',').map((item: string) => item.trim()).filter(Boolean), skills: [...teach.map((skillId) => ({ skillId, direction: 'teach' })), ...learn.map((skillId) => ({ skillId, direction: 'learn' }))] }) });
    if (response.ok) router.push('/dashboard');
  };
  const toggle = (setter: (value: string[]) => void, values: string[], id: string) => setter(values.includes(id) ? values.filter((item) => item !== id) : [...values, id]);
  return <main className="min-h-screen bg-ink px-5 py-12 text-white"><section className="mx-auto max-w-2xl rounded-3xl border border-white/10 bg-white/5 p-8"><p className="text-sm text-mint">Step {step + 1} of 4</p><h1 className="mt-2 font-display text-3xl font-bold">{['Make your profile yours', 'Choose what you teach', 'Choose what you want to learn', 'Set your learning preferences'][step]}</h1><div className="mt-8 space-y-4">{step === 0 && <><input value={form.full_name} onChange={(event) => update('full_name', event.target.value)} placeholder="Full name" className="w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-white" /><input value={form.district} onChange={(event) => update('district', event.target.value)} placeholder="District or city" className="w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-white" /><textarea value={form.bio} onChange={(event) => update('bio', event.target.value)} placeholder="A short introduction" className="min-h-32 w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-white" /></>}{(step === 1 || step === 2) && <div className="grid gap-3 sm:grid-cols-2">{skills.map((skill) => { const selected = (step === 1 ? teach : learn).includes(skill.id); return <button type="button" key={skill.id} onClick={() => toggle(step === 1 ? setTeach : setLearn, step === 1 ? teach : learn, skill.id)} className={`rounded-2xl border p-4 text-left ${selected ? 'border-mint bg-mint/10 text-mint' : 'border-white/10 bg-white/5 text-white/70'}`}><span className="font-semibold">{skill.name}</span><span className="mt-1 block text-xs opacity-60">{skill.category}</span></button>; })}</div>}{step === 3 && <><input value={form.languages} onChange={(event) => update('languages', event.target.value)} placeholder="Languages, separated by commas" className="w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-white" /><select value={form.session_type} onChange={(event) => update('session_type', event.target.value)} className="w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-white"><option>Online</option><option>In-person</option><option>Hybrid</option></select></>}</div><div className="mt-8 flex justify-between"><button type="button" disabled={step === 0} onClick={() => setStep((current) => current - 1)} className="rounded-full border border-white/20 px-5 py-3 disabled:opacity-30">Back</button>{step < 3 ? <button type="button" onClick={() => setStep((current) => current + 1)} className="rounded-full bg-violet px-5 py-3 font-semibold">Continue</button> : <button type="button" onClick={submit} className="rounded-full bg-mint px-5 py-3 font-semibold text-ink">{demo ? 'Save demo profile' : 'Finish profile'}</button>}</div></section></main>;
}
